#!/bin/bash

FAILED_TESTS=""

assertSuccess(){
 local STRATEGY="$1"
 local CMD="$2"
 echo "****************************************************************************"
 echo "** EXECUTE: $CMD";
 eval "$CMD 2>&1"
 local RET="$?"
 echo "**"

 if [ "$RET" != "0" ];then
   echo "** ERROR: execution failed (returncode $RET)"
   FAILED_TESTS="$FAILED_TESTS#assertSuccess => $CMD"
   echo "****************************************************************************"
   if [ "$STRATEGY" = "STOP_ON_ERROR" ];then
      exit 100
   else
      return 100
   fi
 fi
 echo "****************************************************************************"
 return 0
}


echo "*** CLEANUP"
REL="3.2.10-1+xenial"
sudo dpkg -P zabbix-agent-extensions zabbix-agent
sudo rm -rf /etc/zabbix_* /var/log/zabbix /var/run/zabbix zabbix-agent_*.deb zabbix-get_*.deb
wget -c "http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-agent_${REL}_amd64.deb"
wget -c "http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-get_${REL}_amd64.deb"
sudo killall -KILL zabbix_agentd
sudo dpkg -i zabbix-agent_*.deb zabbix-get_*.deb 
sudo sed  -i '~s,# DebugLevel.*,DebugLevel=4,' /etc/zabbix/zabbix_agentd.conf
sudo tail -F /var/log/zabbix/zabbix_agentd.log &

echo "*** TESTS"
assertSuccess STOP_ON_ERROR "sudo dpkg -i zabbix-agent-extensions_*.deb"
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k linux.dmesg | tee /dev/stderr | grep -q -P 'OK: ALL OK|ERROR:'" # Without sudo
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k linux.dmesg | tee /dev/stderr | grep -q 'OK: ALL OK'" # Without sudo
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k linux.multipath | tee /dev/stderr | grep -q 'OK:'" # With sudo
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k vfs.dev.discovery | tee /dev/stderr | grep -q '#BLOCKDEVICE'" # With sudo
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k 'custom.process[zabbix_agentd,minage]'|tee /dev/stderr | grep -q -P '^\d+$'"
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k 'custom.process[zabbix_agentd,maxage]'|tee /dev/stderr | grep -q -P '^\d+$'"
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k 'custom.process[nosuchprocess,maxage]'|tee /dev/stderr | grep -q -P '^\d+$'"
assertSuccess STOP_ON_ERROR "zabbix_get -s localhost -k 'zabbix.agent_extensions.version'|tee /dev/stderr | grep -q -P '^\d+'"
assertSuccess STOP_ON_ERROR 'sudo dpkg -P zabbix-agent-extensions'

echo
echo
echo "*** SUMMARY"
if [ -z "$FAILED_TESTS" ];then
   echo "ALL TESTS PASSED"
   exit 0
else
   echo "THE FOLLOWING TESTS FAILED"
   echo "$FAILED_TESTS"|tr '#' '\n'|sed '~s,^, ,'
   exit 1
fi

