#!/bin/bash

IMAGE_REPO="scoopex666"
IMAGE_NAME="zabbix-agent-with-agent-extensions"
VERSION="${2:-$(git describe --abbrev=0 --tags)}"

if [ "$1" = "build" ];then
   set -x 
   docker rmi ${IMAGE_NAME}:${VERSION}
   docker build -t ${IMAGE_NAME}:${VERSION} -f Dockerfile .
elif [ "$1" = "inspect" ];then
   set -x
   exec docker run --rm --name zabbix-agent-extentions-test -ti ${IMAGE_NAME}:${VERSION} /bin/bash
elif [ "$1" = "publish" ];then
   docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_REPO}/${IMAGE_NAME}:${VERSION}
   docker push ${IMAGE_REPO}/${IMAGE_NAME}:${VERSION}
   docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_REPO}/${IMAGE_NAME}:latest
   docker push ${IMAGE_REPO}/${IMAGE_NAME}:latest
elif [ "$1" = "test" ];then
   echo "TESTING:"
   echo "---"
   echo "docker exec -u root -ti zabbix-agent-extentions-test zabbix_get -s 127.0.0.1 -k zabbix.agent_extensions.version"
   echo "---"
   set -x
   exec docker run --rm \
         --network host \
         -e ZBX_HOSTNAME=zabbix-agent-extentions-test \
         -e ZBX_SERVER_HOST=127.0.0.1 \
         -e ZBX_PASSIVESERVERS=127.0.0.1 \
         --name zabbix-agent-extentions-test ${IMAGE_NAME}:${VERSION}
else
   echo "$0 build|inspect|publish|test"
fi


