#!/bin/bash


######################################################################

VERSION="${1:-$(git describe --abbrev=0 --tags)}"

######################################################################
### HELPERS

prepare(){

	echo "***************************************************************************************************************************************"
	echo "PREPARE"
   set -e
   set -x
	umask 0002
	mkdir -p -m 755 ${TMPDIR}/usr/bin/
	cp -av ${SDIR}/tools/* ${TMPDIR}/usr/bin/
	chmod 755 ${TMPDIR}/usr/bin/*

	mkdir -p -m 755 ${TMPDIR}/usr/share/zabbix-agent-extensions/include.d/
	cp -av ${SDIR}/agent-config/* ${TMPDIR}/usr/share/zabbix-agent-extensions/include.d/
   sed -i "~s,VERSION TO BE REPLACED,${VERSION}," ${TMPDIR}/usr/share/zabbix-agent-extensions/include.d/zabbix_agent_extensions.conf
	chmod 644 ${TMPDIR}/usr/share/zabbix-agent-extensions/include.d/*

	mkdir -p -m 755 ${TMPDIR}/usr/share/zabbix/
	cp -av ${SDIR}/check_payloads/* ${TMPDIR}/usr/share/zabbix/
	chmod 644 ${TMPDIR}/usr/share/zabbix/*

	mkdir -p -m 755 ${TMPDIR}/usr/share/man/man8/
	gzip ${SDIR}/man/httpjson-queryagent.8 -c > ${TMPDIR}/usr/share/man/man8/httpjson-queryagent.8.gz
	chmod 644 ${TMPDIR}/usr/share/man/man8/*

	mkdir -p -m 755 ${TMPDIR}/etc/sudoers.d
	cp ${SDIR}/sudoers ${TMPDIR}/etc/sudoers.d/zabbix
	chmod 0440 ${TMPDIR}/etc/sudoers.d/*

	mkdir -p -m 755 ${TMPDIR}/var/cache/zabbix
   set +x
   set +e
 
}

create_package(){
	TYPE="$1"
   echo "***************************************************************************************************************************************"
   echo "PACKAGE TYPE: $TYPE"
   echo
   set -x
   fpm -s dir -t $TYPE \
		-n zabbix-agent-extensions \
      --license GPLv2 \
      -a all \
	   --deb-no-default-config-files \
      --deb-group root \
      --deb-user root \
      -m "Marc Schoechlin <ms-zabbix-agent-extensions@256bit.org>" \
      --url "https://github.com/scoopex/zabbix-agent-extensions" \
      --after-install ${SDIR}/postinstall \
      -v $VERSION -C $TMPDIR --verbose
   set +x

   if [ "$TYPE" = "deb" ];then
   	dpkg -c zabbix-agent-extensions_*.deb
      RET="$?"
   elif [ "$TYPE" = "rpm" ];then
      rpm -qlp zabbix-agent-extensions*.rpm
      RET="$?"
   fi
   if [ "$RET" != "0" ];then
       echo "ERROR: error on creation of $TYPE package"
       exit 1
   fi
}

create_docu(){
 cd $SDIR/../zabbix_templates/3.2
 ./create_template_documentation
 cd $SDIR/../zabbix_templates/3.4
 ./create_template_documentation
}

######################################################################
### MAIN
if [ -z "$1" ];then
  echo "$0 <version>"
fi

SDIR="$(dirname $(readlink -f $0))/extension-files"

for P in $HOME/.gem/ruby/*/bin/fpm;do
   P="$(dirname $P)"
   export PATH="$P:$PATH"
done

if ( ! (type -a fpm >/dev/null 2>&1 ) );then
   echo "Unable to find 'fpm'"
   exit 100
fi

echo "CREATING VERSION: $VERSION"
rm -rf zabbix-agent-extensions_*.deb zabbix-agent-extensions*.rpm

TMPDIR="$(mktemp -d)"
trap "rm -rf $TMPDIR" EXIT TERM INT

prepare
create_package deb
create_package rpm
create_docu

exit 0
