#!/bin/bash

THE_INCLUDE="Include=/usr/share/zabbix-agent-extensions/include.d/"
if [ -e /etc/zabbix/zabbix_agent2.conf ]; then
 AGENT=zabbix-agent2
 AGENT_INCLUDE=zabbix_agent2.d
 AGENT_CONF=zabbix_agent2.conf
else
 AGENT=zabbix-agent
 AGENT_INCLUDE=zabbix_agentd.d
 AGENT_CONF=zabbix_agentd.conf
fi

if (grep -q -P "Ubuntu|Debian|CentOS|Raspbian" /etc/os-release);then

   if [ -e "/etc/zabbix/$AGENT_INCLUDE/zabbix-agent-extensions" ] || [ -e "/etc/zabbix/$AGENT_INCLUDE/zabbix-agent-extensions.conf" ];then
     echo "Notice: /etc/zabbix/$AGENT_INCLUDE/zabbix-agent-extensions already exists, no need to add the Include to /etc/zabbix/$AGENT_CONF"
   elif ! (grep -q "$THE_INCLUDE" /etc/zabbix/$AGENT_CONF);then  
     echo "" >> /etc/zabbix/$AGENT_CONF
     echo "#################################################################" >> /etc/zabbix/$AGENT_CONF
     echo "# Added by postinstall of package zabbix-agent-extensions" >> /etc/zabbix/$AGENT_CONF
     echo "$THE_INCLUDE" >> /etc/zabbix/$AGENT_CONF_CONF

   fi

   if [ -e "/etc/zabbix/zabbix_agentd2.d/zabbix-agent-extensions" ];then
     echo "Notice: /etc/zabbix/zabbix_agentd2.d/zabbix-agent-extensions already exists, no need to add the Include to /etc/zabbix/zabbix_agent2.conf"
   elif ( [ -e "/etc/zabbix/zabbix_agent2.conf" ] && ! (grep -q "$THE_INCLUDE" /etc/zabbix/zabbix_agent2.conf) );then
     echo "" >> /etc/zabbix/zabbix_agent2.conf
     echo "#################################################################" >> /etc/zabbix/zabbix_agent2.conf
     echo "# Added by postinstall of package zabbix-agent-extensions" >> /etc/zabbix/zabbix_agent2.conf
     echo "$THE_INCLUDE" >> /etc/zabbix/zabbix_agent2.conf
   fi


   usermod -G adm -a zabbix

   mkdir -m 755 -p /var/cache/zabbix
   chown -R zabbix:zabbix /var/cache/zabbix

   mkdir -m 755 -p /etc/zabbix/zabbix-discovery-generic
   chown zabbix:zabbix /etc/zabbix/zabbix-discovery-generic
  
   if (which systemctl >/dev/null 2>&1);then
      echo "Restarting with systemctl"
      systemctl restart $AGENT.service
   elif [ -f /etc/init.d/$AGENT ];then
      echo "Restarting with /etc/init.d/$AGENT"
      /etc/init.d/$AGENT restart

   else
      echo "no known init method"
   fi

   if ( (which systemctl >/dev/null 2>&1) && (systemctl list-unit-files zabbix-agent2.service|grep -q enabled) );then
      echo "Restarting zabbix-agent2 with systemctl"
      systemctl restart zabbix-agent2.service
   elif [ -f /etc/init.d/zabbix-agent2 ];then
      echo "Restarting with /etc/init.d/zabbix-agent2"
      /etc/init.d/zabbix-agent2 restart
   else
      echo "no known init method"
   fi
else
   echo "Notice: no postinstall implemented for you distribution, contributions and merge requests are very welcome ;-)"
fi
