#!/bin/bash

THE_INCLUDE="Include=/usr/share/zabbix-agent-extensions/include.d/"

if (grep -q -P "Ubuntu|Debian|Centos|Raspbian" /etc/os-release);then

   if [ -e "/etc/zabbix/zabbix_agentd.d/zabbix-agent-extensions" ];
   then
     echo "Notice: /etc/zabbix/zabbix_agentd.d/zabbix-agent-extensions already exists, no need to add the Include to /etc/zabbix/zabbix_agentd.conf"
   elif ! (grep -q "$THE_INCLUDE" /etc/zabbix/zabbix_agentd.conf);
   then  
     echo "" >> /etc/zabbix/zabbix_agentd.conf
     echo "#################################################################" >> /etc/zabbix/zabbix_agentd.conf
     echo "# Added by postinstall of package zabbix-agent-extensions" >> /etc/zabbix/zabbix_agentd.conf
     echo "$THE_INCLUDE" >> /etc/zabbix/zabbix_agentd.conf
   fi

   usermod -G adm -a zabbix 

   chown -R zabbix:zabbix /var/cache/zabbix
   mkdir -m 755 -p /var/run/zabbix-generic-discovery/
   chown zabbix:zabbix /var/run/zabbix-generic-discovery/
  
   if (which systemctl >/dev/null 2>&1);then
      echo "Restarting with systemctl"
      systemctl restart zabbix-agent.service
   else
      echo "Restarting with /etc/init.d/zabbix-agent"
      /etc/init.d/zabbix-agent restart
   fi
else
   echo "Notice: no postinstall implemented for you distribution, contributions and merge requests are very welcome ;-)"
fi

