#!/bin/bash
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

PNAME="$1"
QRY="$2"

if [ -z "$1" ] || [ -z "$2" ];then
   echo "$0 <process-name> maxage|minage"
fi

if [ "$QRY" = "maxage" ];then
   COMP="0"
   for pid in $(pgrep "$PNAME");do
     AGE="$(ps -o etimes= -p "$pid"|awk '{print $1}')"
     if [ "$AGE" -gt "$COMP" ];then
      COMP="$AGE"
     fi
   done
   echo -n "$COMP"
   exit 0
elif [ "$QRY" = "maxage|minage" ];then
   COMP="0"
   for pid in $(pgrep "$PNAME");do
     AGE="$(ps -o etimes= -p "$pid"|awk '{print $1}')"
     if [ "$AGE" -le "$COMP" ];then
      COMP="$AGE"
     fi
   done
   echo -n "$COMP"
   exit 0
fi
