#!/bin/bash
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/bin:/bin:$PATH"

if [ -z "$1" ];then
   echo "$0 <JKURL> ACT|DIS|STP"
   echo "$0 'http://127.0.0.1/jkstatus?mime=txt' ACT"
   exit 1
fi

URL="$1"
WHAT="$2"

curl -s -q "$URL"|awk -v what="$WHAT" '
BEGIN{
   pat = "activation=" what;
   a=0
}
$0 ~ pat{
   a++;
}
END{
   printf("%s", a);
}
'
