#!/bin/bash

APPNAME="$1"
DIR="/var/run/zabbix-generic-discovery/"

# Checks
if [ -z "$APPNAME" ];then
   echo -n "NOT SUPPORTED"
   exit 1
fi

if (! echo "$APPNAME"|egrep -q "^[a-zA-Z0-9\.][a-zA-Z0-9\.]*$" );then
   echo -n "NOT SUPPORTED"
   exit 1
fi

cat <<'EOF'
{
   "data":[
EOF

# Example entry
#      {
#         "{#FSNAME}":"\/",
#         "{#FSTYPE}":"rootfs"
#      },

FIRST=1
for FILE in $DIR/$APPNAME-*.json;
do
   if [ "$FIRST" != "1" ];then
      echo -n ","
   fi
   FIRST=0
   cat $FILE
done
cat <<'EOF'
          ]
}
EOF
