#!/bin/bash
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
  

export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/bin:/bin:$PATH"

if [ -z "$1" ];then
   echo "$0 total|biggest|smallest|average"
   exit 1
fi

ps auxwwww|awk -v what="$1" '
   BEGIN{
     a=0;
     c=0;
     max=0;
     min=0;
   }
   /\/httpd2-prefork|\/apache2|\/httpd/{
     a = a + $6; 
     c++
     if ($6 > max){
   max = $6;
     }
     if ((min == 0) || (min > $6)){
   min = $6;
     }
    }
   END{
     if (what == "total"){
      printf("%i",a*1024);
     }else if (what == "biggest"){
      printf("%i",max*1024);
     }else if (what == "smallest"){
      printf("%i",min*1024);
     }else if (what == "average"){
      if (c == 0){
         printf("0");
      }else{
         printf("%i",(a/c)*1024);
      }

     }
   }'

