#!/usr/bin/env ruby
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

require 'yaml'
# /opt/puppetlabs/puppet/cache/state/last_run_summary.yaml
#
# /opt/puppetlabs/puppet/cache/state/agent_disabled.lock
puppet_state = YAML.load_file('/var/lib/puppet/state/last_run_summary.yaml')

value = nil

ARGV.each do |arg|
  if value == nil
    value = puppet_state.fetch(arg)
  else
    value = value.fetch(arg)
  end
end

print "#{value}"
