#!/bin/bash

grep -q "/etc/zabbix/zabbix-agent-extensions.d/" /etc/zabbix/zabbix_agentd.conf  || \
	echo "Include=/etc/zabbix/zabbix-agent-extensions.d/" >> /etc/zabbix/zabbix_agentd.conf


echo "# NO NOT EDIT, INSTALLED BY POSTINSTALL" > /etc/sudoers.d/zabbix
chmod 0440 /etc/sudoers.d/zabbix
echo "Defaults:zabbix !syslog" >> /etc/sudoers.d/zabbix
echo "zabbix     ALL=NOPASSWD: /usr/bin/zabbix_check_multipath" >> /etc/sudoers.d/zabbix

usermod -G adm -a zabbix

/etc/init.d/zabbix-agent restart
chown -R zabbix:zabbix /var/cache/zabbix
