#!/bin/bash

APPNAME="$1"
DIR="/var/run/zabbix-generic-discovery/"

# Checks
if [ -z "$APPNAME" ];then
   echo -n "NOT SUPPORTED"
   exit 1
fi

if (! echo "$APPNAME"|egrep -q "^[a-zA-Z0-9\.][a-zA-Z0-9\.]*$" );then
   echo -n "NOT SUPPORTED"
   exit 1
fi


if ( ! [ -d "$DIR/$APPNAME/" ] ) ;then
   echo -n "NOT SUPPORTED"
   exit 1
fi

cat <<'EOF'
{
   "data":[
EOF

# Example entry
#      {
#         "{#FSNAME}":"\/",
#         "{#FSTYPE}":"rootfs"
#      },

cat $DIR/$APPNAME/*.json
cat <<'EOF'
          ]
}
EOF
