name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/heads/main
      - name: Setup
        run: |
          sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan wget -y
          sudo gem install fpm
      - name: Build Package
        run: ./create_packages
      - name: Test Package
        run: sudo ./ci_test
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "zabbix-agent-extensions*.deb,zabbix-agent-extensions-*.rpm"
