name: Shared Build Workflow

on:
  workflow_call:
    inputs:
      publish_steps:
        description: "Publish artefacts"
        required: false
        default: false
        type: boolean

jobs:
  build-and-release:
    name: CI-PKGs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        run: |
          sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan wget -y
          sudo gem install fpm
      - name: Build Package
        run: ./create_packages
#      - name: Test Package
#        run: sudo ./ci_test
      - name: Build and test container image zabbix-agent
        run: |
          ./create_docker -t zabbix-agent test
      - name: Build and test container image zabbix-agent2
        run: |
          ./create_docker -t zabbix-agent2 test
      # Publish release
      - uses: ncipollo/release-action@v1
        if: ${{ inputs.publish_steps }}
        with:
          artifacts: "zabbix-agent-extensions*.deb,zabbix-agent-extensions-*.rpm,kubernetes/zabbix-agent*-daemonset-kubernetes-release.yaml"
      - name: Login to Docker Hub
        if: ${{ inputs.publish_steps }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish docker images for zabbix-agent
        if: ${{ inputs.publish_steps }}
        run: |
          ./create_docker -t zabbix-agent publish
      - name: Publish docker images for zabbix-agent2
        if: ${{ inputs.publish_steps }}
        run: |
          ./create_docker -t zabbix-agent2 publish
